//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computadores.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesComp
    {
        public int Codigo { get; set; }
        public string NombreImagen { get; set; }
        public int CodigoComputador { get; set; }

        [JsonIgnore]
        public virtual Computador Computador { get; set; }
    }
}
