//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computadores.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Codigo { get; set; }
        public string CodigoAgencia { get; set; }
        public string CodigoCliente { get; set; }
        public int CodigoComputador { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public int Valor { get; set; }

        [JsonIgnore]
        public virtual Agencia Agencia { get; set; }

        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }

        [JsonIgnore]
        public virtual Computador Computador { get; set; }
    }
}
